### ISSUE TITLE
Omit Pick and other utility tyles

### ISSUE THREAD

**Issue by fhewitt** [lukeautry/tsoa#500] opened 2019-10-03 15:09 UTC
## Sorting

* **I'm submitting a ...**
  - [X] feature request

* I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
With a type like
```
export interface Foo {
  id: string;
  value: string;
}

export interface Bar extends Pick<Foo, 'value'> {
  is: boolean
}
```

I would like TSOA to resolve correctly (Yes I know, I'm never satisfied!) If TSOA can't resolve external library, it should probably be able to resolve

## Current Behavior

Error: No matching model found for referenced type Omit. If Omit comes from a dependency, please create an interface in your own code that has the same structure. Tsoa can not utilize interfaces from external dependencies. Read more at htt
ps://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD

Same for `Pick`

## Context (Environment)
Version of the library: 2.5.4
Version of NodeJS: 10.14.1
* Confirm you were using yarn not npm: [X]

## Detailed Description
I would like https://www.typescriptlang.org/docs/handbook/utility-types.html - starting with Omit and Pick that I use more often - to resolve properly.

## Breaking change?
No, just add new usage cases, and should not affect the one that works already.

**Comment by fhewitt** [comment] 2019-10-03 15:10
I imagine it represents tremendous amount of work, maybe even in depth refactoring... And I have absolutely no time right now, but if someone can point me quickly where / how the work should be done, I hope for some free programming time end November or December (if no one take it before).

**Comment by dgreene1** [comment] 2019-10-03 15:19
Duplicate of https://github.com/lukeautry/tsoa/issues/372

**Closed by dgreene1** 2019-10-03 15:19 UTC
