### ISSUE TITLE
Dynamic Query/Header Param

### ISSUE THREAD

**Issue by oreporan** [lukeautry/tsoa#353] opened 2019-05-14 19:03 UTC
I have a request which should look like this

`users/query?someKey=someValue&someKey2=someValue2`

These are dynamic query params that I handle in the server. Is there any way to create this using tsoa?

I tried something like this - 

```ts
export interface QueryFilters {
    [x: string]: string;
}
```

```ts
...
 public async get(
        @Query() filters?: QueryFilters
    ): Promise<User[]> {
        return getUsers(filters);
    }
```

but I'm getting error - 
```
 Error: @Query('filters') Can't support 'refObject' type.
```

**Comment by HoldYourWaffle** [comment] 2019-06-15 19:19
I'm currently working on an implementation of `refObject` for `@Query` (and possibly `@Header` too) by "flattening" the properties as individual parameters and reassembling them at the server.

I have a **very basic** but (mostly) working implementation ready, which is good enough for my own project for now. When I have the time I'll add the missing parts and create a PR.

**Comment by dgreene1** [comment] 2019-08-17 05:31
@HoldYourWaffle we’d love if you could submit your PR for this.
@dmitrirussu had a similar and interesting request here: https://github.com/lukeautry/tsoa/issues/324#issue-391707399

I also work with another team that would find this really valuable as they use OData filters. So suffice to say, you’d be quite the hero if you were to submit this! :)

**Comment by HoldYourWaffle** [comment] 2019-08-22 16:14
Sorry for the late response, haven't touched this in a while due to summer break.

I don't remember much and I'm not able to really look into the code right now, but from what I remember my implementation was very basic and specific to my use-case. I'll see what I can do to fix it up and maybe make it more usable for other use-cases.

**Comment by dgreene1** [comment] 2019-08-30 00:12
I believe that https://github.com/lukeautry/tsoa/issues/219#issuecomment-526403819 is a duplicate of this. I’ll close that one to keep this open.

**Comment by dgreene1** [comment] 2019-08-30 00:15
@Templum @anro87 when we introduce array like query params then this is the issue number to track. I’m cc’ing you so you’re not left out. We apologize that your original feature request was not added in a timely manner.

**Comment by givethemheller** [comment] 2020-03-27 23:23
@WoH can you point me to where the changes in the code would need to be to get this working? Its currently blocking for me. Would be happy to work on it (maybe tonight/this weekend)

**Comment by WoH** [comment] 2020-03-30 14:21
This should not be a blocker, albeit you'd have to write the OpenAPI for yourself. Assuming Express, but you can inject the `Request` (and look at req.headers) and add the Spec to your tsoa.json.
I'm not sure how the API should look like for this, the one suggested is a non-starter.
`@Query() filters` would be a query param called filters, as in `?filters=`.
I could imagine resolving an interface here, but the approach would have to ensure a) you can still pull off individual query params, b) these would not be documented twice, c) the OpenAPI Spec is sound.

**Comment by moshewe** [comment] 2020-04-07 07:34
> the one suggested is a non-starter.

It's very Javascript-esque to just get a params object. Would it not be possible to "break down" the interface/class given as a type? E.g. `@Query queryObject: IQueryParams` can be converted into `@Query qObjectProp1: prop1Type, @Query qObjectProp2: prop2Type, ...`

A possible conflict with this solution is when we have something along the lines of `@Query params, @Query('paramName') myParam: paramType`, breaking down the params object will yield a duplicate `myParam`. But I guess that's something easy to handle.

**Comment by WoH** [comment] 2020-04-07 08:59
The idea (getting the spec from an interface) is fine, we just need a way to indicate that it's a query param collection, not, for example, an object serialized from one query param.
I could see something like `@Query('/') params: { one: string, two: number }`, since it's impossible to use `/` as the name of a single query param.

**Comment by moshewe** [comment] 2020-04-16 20:26
You are correct. I was a bit confused there because we're using `nest.js` decorators for our controllers and `tsoa` "automagically" works with those. A `@QueryParams()` decorator seems the logical way forward, but your idea of using a wildcard such as `/` is better (and also keeps things working with `nest` 😄 ).

**Comment by WoH** [comment] 2020-04-16 20:30
If anyone wants to implement this, I'd be glad to review a PR adding this.

**Comment by mp205** [comment] 2021-10-31 01:03
any update on this?

**Comment by KenEucker** [comment] 2021-12-03 03:39
@WoH, just to clarify about where this issue is. You are hoping for a PR that implements this:
`@Query('/') params: { one: string, two: number }`

Is that correct?

**Comment by WoH** [comment] 2021-12-03 10:33
Yes. The validation layer can already do that for bodies, so there should be a decent amount of reuse possible. Similarly, the ParamGenerator already can tell you if a type makes sense for a single query Param, ideally we'd check in these cases as well

**Comment by u12206050** [comment] 2022-01-27 09:00
Any update on this, this would make tsoa compatible with FeathersJS which currently bundles all params into a single `params` object, so would be nice if this worked.

**Comment by u12206050** [comment] 2022-01-27 09:01
Typical use case of multiple params are: `{filter: string, limit: number, skip: number, orderBy: string, orderDirection: 'DESC' | 'ASC'}`

**Comment by luke-lewandowski** [comment] 2022-03-22 05:23
Has anyone got it working yet for any project? We are looking at implementing OData and this would be super helpful.

**Closed** 2023-12-28 19:36 UTC
Labels: enhancement, help wanted

**Comment by WoH** [comment] 2024-04-19 08:45
> This would certainly be a neat feature imo. It's those simple things like
> 
> ```typescript
> interface Page {
>   index: number;
>   size: number;
> }
> 
> @Get('/items')
> public async getItems(@Query() page: Page) {
>   return itemService.getAll(page);
> }
> ```
> 
> that would safe alot of boilerplace imo - although this doesn't work with default values..

What about `@Queries() qs: Page` isn't working for you?

**Comment by falk-stefan** [comment] 2024-05-02 17:48
@WoH Oh, I honestly didn't know about that one. I'm rather new to tsoa. Thank you for the hint!

**Comment by douglasg14b** [comment] 2024-09-16 23:45
I assume that `@Queries queryParams: { someEnum: string[] }` is not supported since i get:

```
@Queries('queryParams') only support 'refObject' or 'nestedObjectLiteral' types. If you want only one query parameter, please use the '@Query' decorator.
```

**Comment by dessalines** [comment] 2025-01-22 04:27
I really need the `type`, not interface version, as that's what is generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). This library is currently unusable for rust API's, since `Query()` nor `Queries()` doesn't support `type`
