### ISSUE TITLE
No matching model found for referenced type "Name of type".

### ISSUE THREAD

**Issue by dimacros** [lukeautry/tsoa#876] opened 2020-12-26 18:02 UTC
This error is supposed to happen when you try to use types or interfaces from node_modules, but in this case I am just using "paths" aliases that you can set in tsconfig.json. In conclusion, the error does not check if it is an alias and it assumes that if there are no relative paths it is an external module.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior
Generate routes

## Current Behavior
Error: No matching model found for referenced type "Name of type". If "Name of type" comes from a dependency, please create an interface in your own code that has the same structure. Tsoa can not utilize interfaces from external dependencies. Read more at https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD 

## Possible Solution
Check if it is an alias in tsconfig.

## Steps to Reproduce

 Configure "paths" in tsconfig.json -> compilerOptions

## Context (Environment)

Version of the library:  latest
Version of NodeJS:  10

- Confirm you were using yarn not npm: [ npm]

**Comment by WoH** [comment] 2021-01-03 06:31
Duplicate of #868, the current solution is outlined in the issue description.

**Closed by WoH** 2021-01-03 06:31 UTC
