### ISSUE TITLE
Including `length` as an enum value breaks spec generation

### ISSUE THREAD

**Issue by arcticfly** [lukeautry/tsoa#1523] opened 2023-12-18 09:28 UTC
The word `length`, if included as part of the enum returned by a route on a controller, prevents the spec from being generated properly.

## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submitted

## Expected Behavior

The openapi documentation should have generated as normal.

```yaml
components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas: {}
    securitySchemes:
        Authorization:
            type: http
            scheme: bearer
info:
    title: 'OpenPipe API'
    version: 1.0.1
    description: 'The public API for reporting calls and generating inference with OpenPipe.'
openapi: 3.0.0
paths:
    /basic:
        post:
            operationId: CreateChatCompletion
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                type: string
                                enum:
                                    - hi
                                    - there
                                    - length
            security: []
            parameters: []
servers:
    -
        url: /api/v2
```

## Current Behavior

No yaml file was generated. Instead, I see the following error: 

```
node_modules/@tsoa/cli/dist/swagger/specGenerator3.js:556
                    enumValuesByType[type.type][enumValue] = enumValue;
                                                           ^

RangeError: Invalid array length
    at SpecGenerator3.groupEnums
```

## Steps to Reproduce

newControllers/basicController.ts:
```
import { Controller, Post, Route } from "tsoa";

@Route("basic")
export class BasicController extends Controller {
  @Post()
  public async createChatCompletion(): Promise<"hi" | "there" | "length"> {
    console.log("in basic controller");

    await new Promise((resolve) => setTimeout(resolve, 1000));
    return "hi";
  }
}
```

generate.ts:
```
  const swaggerDocsSpecOptions: ExtendedSpecConfig = {
    noImplicitAdditionalProperties: "ignore",
    controllerPathGlobs: [TSOA_BASE_PATH + "/newControllers/*Controller.ts"],
    basePath: "/api/v2",
    entryFile: "src/server.ts",
    securityDefinitions: {
      Authorization: {
        type: "http",
        scheme: "bearer",
      },
    },
    specVersion: 3,
    outputDirectory: TSOA_BASE_PATH + "/generated",
    name: "OpenPipe API",
    description: "The public API for reporting calls and generating inference with OpenPipe.",
    version: "1.0.1",
  };

  await generateSpec(swaggerDocsSpecOptions);
```

1. Run `tsx generate.ts`

1. 2. 3. 4.

## Context (Environment)

Version of the library: 5.1.1
Version of NodeJS: 20.3.1

- Confirm you were using yarn not npm: [ ]

## Detailed Description

I'd like to be able to use `length` as a potential enum value and still be able to generate openapi docs.

**Comment by jackey8616** [comment] 2024-01-16 02:16
I think this issue is no longer exists @ 6.0.1.
I cannot reproduce it.

@WoH please consider close this issue.

**Closed** 2024-01-16 07:51 UTC
Labels: bug, help wanted, good first issue
