### ISSUE TITLE
Problem resolving type, not from dependency

### ISSUE THREAD

**Issue by devnev** [lukeautry/tsoa#724] opened 2020-06-05 13:53 UTC
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

This might be the related to #477.

## Steps to Reproduce

Create the following files and run `yarn install && yarn tsoa spec-and-routes` and I get an error
```
There was a problem resolving type of 'api.File'.
Generate routes error.
 Error: No matching model found for referenced type _File. If _File comes from a dependency, please create an interface in your own code that has the same structure. Tsoa can not utilize interfaces from external dependencies. Read more at https://github.com/lukeautry/tsoa/blob/master/docs/ExternalInterfacesExplanation.MD
 in 'FooController.bar'
```

`controllers/foo.ts`
```ts
import api from '../models/api';
import {
  Route,
  Get,
  Res,
  TsoaResponse,
} from 'tsoa';

@Route('foo')
export class FooController {
    @Get('bar')
    public async bar(
        @Res() created: TsoaResponse<201, {file: api.File}>,
    ): Promise<void> {
        return created(201, {file: {name: 'test'}});
    }
}
```

`models/api/index.ts`
```ts
// models/api/index.ts
import _File from './file';

namespace Api {
  export type File = _File;
}

export = Api;
```

`models/api/file.ts`
```ts
export interface File {
    name: string;
}

export default File;
```

Remaining files are for completeness (and making sure the typescript options match) but less relevant.

`index.ts`
```ts
export default {};
```

`package.json`
```json
{
  "name": "tsoa-test",
  "version": "0.0.1",
  "main": "index.ts",
  "license": "MIT",
  "devDependencies": {
    "tsoa": "^3.1.1"
  }
}
```

`tsconfig.json`
```json
{
    "compilerOptions": {
        "outDir": "./dist",
        "target": "ES6",
        "esModuleInterop": true,
        "moduleResolution": "node",
        "lib": ["ES6"],
        "module": "CommonJS",
        "strict": true,
        "skipLibCheck": true,
        "isolatedModules": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "include": [
        "./**/*"
    ],
    "exclude": [
        "node_modules",
        "dist"
    ]
}
```

`tsoa.json`
```json
{
  "entryFile": "index.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
  "controllerPathGlobs": ["controllers/**/*.ts"],
  "spec": {
    "outputDirectory": "tsoa-gen",
    "specVersion": 3
  },
  "routes": {
    "routesDir": "tsoa-gen"
  }
}
```

## Expected Behavior

No exceptions thrown, routes and spec generated successfully.

## Context (Environment)

Version of the library: 3.1.1
Version of NodeJS: 14.2
- Confirm you were using yarn not npm: [x]

**Comment by WoH** [comment] 2020-06-06 15:51
I believe this is indeed a duplicate of #477 (and thererfore closing it). Dan has mentioned the workaround and reason why (we, the maintainers) don't have this as a priority feature. Similat to what he said, we'd welcome contributions to support this.

**Closed by WoH** 2020-06-06 15:51 UTC
