### ISSUE TITLE
Subresources

### ISSUE THREAD

**Issue by Recodify** [lukeautry/tsoa#318] opened 2018-11-27 21:51 UTC
Currently it there anyway to support sub resources? To explain what I mean by this:

resource = "/company"
resource="/user"
subResource = "/company/{companyId}/users"

I've tried to get this behavior by creating a `CompanyUserController` with `@Route('company/{companyId}/users')` this generates the correct route header in the docs but the ahref of the header is not correct and I am able to access the route via postman. Is this possible with the current implementation or do I need to implement this myself?

**Comment by lukeautry** [comment] 2018-11-27 21:57
Not through the route decorator. You could definitely implement it at the method decorator level (GET, POST, etc). I think it could be implemented at the route decorator level if you want to take a stab at it. The tricky thing would be verifying that each method within the controller properly accepts the path parameter (e.g. {companyId}).

**Comment by Recodify** [comment] 2018-11-27 22:02
Thanks for the speedy response Luke, let me have a play and see what I can come up with.

**Comment by endor** [comment] 2018-11-28 08:46
Is this a duplicate of https://github.com/lukeautry/tsoa/issues/261?

**Comment by lukeautry** [comment] 2018-12-08 16:44
I would say so. Closing this issue in favor of #261.

**Closed by lukeautry** 2018-12-08 16:44 UTC
Labels: enhancement, help wanted
