### ISSUE TITLE
Allow models in node_modules in some cases.

### ISSUE THREAD

**Issue by pgraham** [lukeautry/tsoa#784] opened 2020-09-14 15:59 UTC
Hi,

I've run into the "No matching model found for referenced type" error and have read the explanation and understand the reasons for not supporting this in a general way.

However, I think that for point 2 "Architectural/Quality Problem", there is an assumption being made that any modules in node_modules are 3rd party. In my case, we maintain a private module that contains interfaces/behaviour that is shared across several micro-services and is published through a private node repository.

In this case, having to create a duplicate interface in each micro-service is an unjustifiable level of maintenance overhead and having the documentation update by updating the dependency is a feature and not a bug.

I'm wondering if it would be possible to allow an accepted list of packages in node_modules that can publish model definitions. My initial thought is something like:

_tsoa.json_
```
{
  spec: {
    externalModelPackages: [
      "@abc/my-package",
      "@def/*" <-- Maybe allow wildcard for private scope?
    ]
  }
}
```

I'd be willing to work on a PR to support this (or something similar), but would need some assurance that this would/could be accepted before spending any time on it.

Thanks!
 
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [X] feature request
  - [ ] support request

- I confirm that I
  - [X] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

Allow model definitions to be found in an explicit list of accepted packages in node_modules.

## Current Behavior

All model definitions must not be in node_modules

**Comment by WoH** [comment] 2020-09-14 16:50
Closed as duplicate of #774

**Closed by WoH** 2020-09-14 16:50 UTC
