### ISSUE TITLE
Async chain broken in koa authentication middleware

### ISSUE THREAD

**Issue by yolofy** [lukeautry/tsoa#247] opened 2018-07-11 15:12 UTC
My async controller functions are returning 404 when using the koa authenticateMiddleware. Please don't break the chain.

Current generated code 
```
function authenticateMiddleware(security: TsoaRoute.Security[] = []) {
        return (context: any, next: any) => {
            let responded = 0;
            let success = false;
            for (const secMethod of security) {
                koaAuthentication(context.request, secMethod.name, secMethod.scopes).then((user: any) => {
                    // only need to respond once
                    if (!success) {
                        success = true;
                        responded++;
                        context.request['user'] = user;
                        next();
                    }
                })
                    .catch((error: any) => {
                        responded++;
                        if (responded == security.length && !success) {
                            context.status = error.status || 401;
                            context.body = error;
                            next();
                        }
                    })
            }
        }
    }
```
Working async code
```
function authenticateMiddleware(security: TsoaRoute.Security[] = []) {
        return async (context: any, next: any) => {
            let responded = 0;
            let success = false;

            for (const secMethod of security) {
                try {
                    const user = await koaAuthentication(context.request, secMethod.name, secMethod.scopes);
                    if (!success) {
                        success = true;
                        responded++;
                        context.request['user'] = user;
                        await next();
                    }
                }
                catch (error) {
                    responded++;
                    if (responded == security.length && !success) {
                        context.status = error.status || 401;
                        context.body = error;
                        await next();
                    }
                }
            }
        }
    }
```

**Comment by yolofy** [comment] 2018-07-12 10:53
More info on this: https://github.com/alexmingoia/koa-router/issues/358#issuecomment-350440180

**Comment by cjam** [comment] 2018-07-16 23:07
I'm having issues using the authentication feature and I'm not sure if it's related to this issue, or maybe I'm just unsure on how this feature should work.  I have an two different types of security:

```ts
export async function koaAuthentication(request: Request, securityName: string, securityScopes: string[] = DEFAULT_SCOPES): Promise<any> {
    const securityType : SecurityType = securityName as any;
    const scopes : Scopes[] = securityScopes as any;
    if (securityType === 'siteminder') {
        const siteminderHeaders = getSiteminderHeaders(request);
        console.log(siteminderHeaders);
        if (siteminderHeaders && siteminderHeaders.guid) {
            return siteminderHeaders;
        } else {
            throw new Error('bla that didnt work');
        }
    }

    if (securityType === 'jwt') {
        // const token = request.body.token || request.query.token || request.headers['x-access-token'];
        const token = request.ctx.cookies.get(TOKEN_COOKIE_NAME);
        await new Promise((resolve, reject) => {
            if (!token) {
                reject(new Error("No token provided"))
            }
            jwt.verify(token, JWT_SECRET, function (err: any, decoded: any) {
                if (err) {
                    reject(err)
                } else {
                    // Check if JWT contains all required scopes
                    for (let scope of scopes) {
                        if (!decoded.scopes.includes(scope)) {
                            reject(new Error("JWT does not contain required scope."));
                        }
                    }
                    resolve(decoded)
                }
            });
        });
    }

    throw new Error('Unknown Security Type');
}
```

And I have a single secure endpoint that I would like to use to generate a jwt for subsequent requests:

```ts
    @Get()
    @Security('siteminder')
    public token(@Request() request: koa.Request) {

        return 'willbeatoken';
    }
```

Now in this case, I would expect that if the security function returns a rejected promise that this endpoint wouldn't even be executed, but looking at the code i can see where it is calling the next middleware.  In this case, this endpoint will always return a 200 with the content shown above.  I would have expected that the auth middleware would have jumped in and returned a 401.  It seems that I am definitely missing something.  I couldn't find any tests that were exercising this type of case but it could be that I'm using it wrong.

Thanks for any help.

**Comment by cjam** [comment] 2018-07-18 13:50
To comment on the original issue:

@yolofy Could you also prevent 'breaking the chain' by returning the `next()` (based on https://github.com/alexmingoia/koa-router/issues/358#issuecomment-379617180)?   

Either way, it seems that the `promiseHandler` may also need to return / `await` the calls to `next` as well: 

https://github.com/lukeautry/tsoa/blob/32763f92f8e447435563d9a5ff39f3e9252fadaf/src/routeGeneration/templates/koa.ts#L104-L132

I fixed my issue by modifying the routeTemplate to ditch out before calling the controller if the status of the context has already been set to an error status, otherwise, the controller will override the status and body.

```handlebars
export function RegisterRoutes(router: any) {
    {{#each controllers}}
    {{#each actions}}
        router.{{method}}('{{fullPath}}',
            {{#if security.length}}
            authenticateMiddleware({{json security}}),
            {{/if}}
            async (context, next) => {
            const args = {
                {{#each parameters}}
                    {{@key}}: {{{json this}}},
                {{/each}}
            };

            let validatedArgs: any[] = [];
            try {
              validatedArgs = getValidatedArgs(args, context);
            } catch (error) {
              context.status = error.status || 500;
              context.body = error;
              return next();
            }

            {{#if security.length}}
                // Check to see if authentication has failed, if so don't execute controller method
                if(context.status && context.status === 401){
                    return next();
                }
            {{/if}}

            {{#if ../../iocModule}}
            const controller = iocContainer.get<{{../name}}>({{../name}});
            {{else}}
            const controller = new {{../name}}();
            {{/if}}

            const promise = controller.{{name}}.apply(controller, validatedArgs);
            return promiseHandler(controller, promise, context, next);
        });
    {{/each}}
    {{/each}}
```

**Comment by x1yy** [comment] 2018-09-13 20:56
i get this error too. do i need to modify the core to fix?

**Comment by x1yy** [comment] 2018-09-13 21:30
Oh, i can create custom template from main koa template and change the `authenticateMiddleware`

**Comment by technicallyfeasible** [comment] 2018-12-13 10:43
Although this can be circumvented with a custom template I cannot believe that this bug has been open for half a year. It's a major bug that prevents the use of async authentication middleware.

**Comment by lukeautry** [comment] 2018-12-13 16:47
Hey all - I put in a fix for this in 2.3.7. Let me know if you're still seeing problems. Sorry for the long delay.

I think these handlers were written without a real understanding of Koa and its promise-based handling. Things like calling Promise.all but not returning the result, not awaiting next(), etc.

**Closed by lukeautry** 2018-12-13 16:47 UTC

**Comment by technicallyfeasible** [comment] 2018-12-13 17:06
thanks a lot, just created a pull request with the fix but I guess I was a bit too slow ;-)

**Comment by lukeautry** [comment] 2018-12-13 17:08
No problem @technicallyfeasible - since you're familiar with the problem, it would be great if you could confirm that the new version fixes the issue for your project.

**Comment by technicallyfeasible** [comment] 2018-12-13 18:10
yes @lukeautry, the issue is now fixed
