### ISSUE TITLE
Clarifying what "refactors for the sake of refactoring" means

### ISSUE THREAD

**Issue by HoldYourWaffle** [lukeautry/tsoa#457] opened 2019-08-31 09:07 UTC
## Sorting

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [ ] support request
  - [x] discussion point (@dgreene1 should this be added to the template?)

* I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Current Behavior
This is the section of the contributing guide I want to talk about:

> Note that it is unlikely the project will merge refactors for the sake of refactoring. These types of pull requests have a high cost to maintainers in reviewing and testing with little to no tangible benefit.

When I read this for the first time the first thing that came to my mind was: "When is a refactor a refactor for the sake of refactoring?", and after that: "What about actual *useful* cleanups?".
**I'm not aiming for another philosophical debate about software development here**, I think we've debated that issue enough in #445. However, I think (or at least hope) that we can all agree that completely closing the door for code quality/readability/accessibility improvements is neither necessary nor desirable, and that *significantly* improving code quality has an actual tangible benefit to the project (at least in the long-run).

## Expected Behavior
I hope that we can keep an open-mind about these kind of improvements that are actually useful. Perhaps that was already the intention, in which case this is just a clarification.

## Detailed Description
I think most of mine and @dgreene1's arguments on this matter are already listed in #445.
Some of my notable points were:
- The current code (at least in the areas I checked) can be really confusing or opaque to newcomers
- There's a lot of "low hanging fruit" when it comes to typesafety improvements, which might require some refactoring (I'd argue that this wouldn't be a "refactor for refactoring's sake" even with the current guide)
- Locking into "how things are now because it works" doesn't promote a healty and clean codebase or continuous quality improvements
- This code isn't big enough to *need* this kind of bureaucracy for sanity

Please look at #445 for a more detailed explanation of my reasoning and some additional minor points.

## Possible Solution
I think the contributing guide should be clarify what *isn't* a "refactor for the sake of refactoring". My take would be something like this:

> Note that it is unlikely the project will merge refactors for the sake of refactoring. These types of pull requests have a high cost to maintainers in reviewing and testing with little to no tangible benefit _in most cases. If you think your idea is an actually valuable refactor, please create an issue explaining your reasoning first. Valuable refactors are ones that **significantly** increase code readability, quality, accessibility for new contributors or typesafety; without increasing redundancy or complexity, decreasing flexibility or breaking existing functionality._

The cursive part is new. Feel free to criticize my grammar, it's still early...

## Disclaimer
I'm not trying to restart the discussion from #445 (which was focused on the wrong thing in my opinion), nor am I trying to "push my will" (or typeResolver cleanup). I just hope we can have a healthy (and short) debate on where the line lays for "refactoring for the sake of refactoring". I think it should lay before the kind of improvements I've listed above, but I'm interested in what the other contributors think about this.

**Comment by dgreene1** [comment] 2019-08-31 11:45
> Locking into "how things are now because it works" doesn't promote a healty and clean codebase or continuous quality improvements

I don’t appreciate the repeated suggestion that I am not a proponent of refactoring. To the contrary, I always try to improve the readability, the performance, and design of the code. The only difference is that I do that while I am introducing a feature or fixing a bug so that it’s easier for the code reviewer to quickly see what was changed and why.

To further cement that I am an advocate of refactoring, here are specific examples from my tsoa contributions:

### Developer experience

My PR

**Comment by dgreene1** [comment] 2019-08-31 12:27
To further cement that I am an advocate of refactoring, here are specific examples from my tsoa contributions:

* My PR that added the noImplicitAdditionalProperties has multiple pieces of code that I refactored:
  * I refactored some types to make it easier to ensure that I was covering every possible type case. Not only did I make that refactor so that I could more easily add the feature, but I also did my code reviewers a favor by adding a github comment that explained the rationale for the change: https://github.com/lukeautry/tsoa/pull/385/files#discussion_r310637426
  * You’ll see that I also refactor the way our tests are run and I modified our VSCode configurations. However, I did that to make it easier to add the test coverage for the new feature. On top of that, I made sure to add an explanation of the rationale [in the PR summary](https://github.com/lukeautry/tsoa/pull/385) so that I could again make it easier for the code reviewer to understand why the code changed.
* My PR https://github.com/lukeautry/tsoa/pull/386/files introduced a code change but it also introduced documentation to help the user.
  * you’ll notice something interesting about that PR, which is that I had to fix a broken test that was unrelated to the issue at hand and [it confused the code reviewer.](https://github.com/lukeautry/tsoa/pull/386/files#discussion_r310905252) This is a perfect example of why it’s important to only change code that exists within the scope of the proposed change (the scope being defined by the feature or bug that is being added/fixed).

So hopefully this clarifies that I believe deeply in refactoring, but that I think it must be done in a way that respects the time of the code reviewer. The contributor guidelines clarify that point.

> However, I think (or at least hope) that we can all agree that completely closing the door for code quality/readability/accessibility improvements is neither necessary nor desirable

Where did you get the idea that we don’t want improvements? In the last few months since I’ve taken over tsoa, the library has seen its largest and most useful enhancements reviewed and merged. Additionally, there are many active projects in the works to completely revamp the way that tsoa works under the hood: https://github.com/lukeautry/tsoa/issues/416

> This code isn't big enough to need this kind of bureaucracy for sanity

This comment baffles me because the limiting factor is not the size of the code. The limiting factor is my time. And in order for me to best serve the tsoa community, I have to “communicate my needs” and to “maintain boundaries” in order to keep my sanity. I am sad that you view that as bureaucracy. In reality, the first draft of the contributor guidelines are simply a pragmatic approach to development. If I have (let’s say) 3 hours a week to spend on tsoa, should I spend that 3 hours:

* reviewing refactoring to make sure that it doesn’t cause regressions (because any time you touch code you risk a regression)
* or should I spend that time reviewing PRs that have new features?

I think everyone would agree that time is best spent reviewing new features and bug fixes. And I would expect that the existing code is refactored as part of of the PR (in a manner similar to my personal examples above). I have learned this from Martin Fowler who said, “When you find you have to add a feature to a program, and the program's code is not structured in a convenient way to add the feature, first refactor the program to make it easy to add the feature, then add the feature.“

But if a PR does not fix a bug or add a new feature, then it is by definition “refactoring for refactoring sake.” While the refactoring may be useful, its utility is less than that of a standard feature/bug PR. The contributor guidelines (that I took from elastic search’s page), do not state that refactor PRs “won’t” be merged, it only states that they are “unlikely.”

The reason why we are unlikely to accept a PR that includes refactors without added features or bugs is that every PR can introduce new bugs. Please see this [wonderful StackOverflow thread about the concerns of bugs that are introduced by refactoring.](https://softwareengineering.stackexchange.com/questions/193953/how-many-regression-bugs-from-refactoring-is-too-many/193961) The point is that all changes involve risk, and mitigating risk requires time from the reviewer. I am much more interested in reviewing the code is the value (ie the user getting a new feature or a fixed bug) outweighs the risks (that a refactor introduces a [latent bug](https://softwareengineering.stackexchange.com/questions/193953/how-many-regression-bugs-from-refactoring-is-too-many/193961)).

> I hope that we can keep an open-mind about these kind of improvements that are actually useful. Perhaps that was already the intention, in which case this is just a clarification.

We do have our minds open to refactoring. We also have our minds open to what contributions should look like as illustrated by the issue thread Luke started here: https://github.com/lukeautry/tsoa/issues/449 which is where I would suggest that this discussion continue. So although this issue thread is a duplicate of https://github.com/lukeautry/tsoa/issues/449, I will leave it open in the spirit of openness and learning.

**Comment by lukeautry** [comment] 2019-08-31 15:06
If anyone hasn't read it, I highly recommend Martin Fowler's [Refactoring](https://martinfowler.com/articles/refactoring-2nd-ed.html). It's a book that helped clarify my thinking around what refactoring is and isn't when it should be done, and why it should be done.

At a high level, if `tsoa` worked perfectly and had every feature, then refactoring would probably not matter too much. This obviously isn't how software development works.

I'm not opposed to standalone refactorings, and in fact, I think they should come in that form, but they should be tied into some specific feature initiative. In other words, we are refactoring X, so that we can more easily extend the program to do Y. If X is confusing or has bad readability, it's quite reasonable to refactor it to get it into a place where it can be easily changed.

That's really the only requirement, in my mind. Make the code easier to change, then make the change, but the end goal is always to ship something new.

**Comment by dgreene1** [comment] 2019-08-31 17:18
That’s fine Luke, but as someone who only recently starting understanding the internals of tsoa, I would not be qualified to review most PRs that are purely refactoring. So I think I’m doing people a favor by essentially saying, “a refactoring PR might languish for a long time until Luke can check this out.”

However, if it’s a small, targeted refactor of code that I have worked in before, then I have more of a chance of being successful at assuring the quality of my review. But until my familiarity of the codebase grows, I found it important to clarify my limitations. Adopting the elastic search contributor guidelines was the best way for me to do so.

So @lukeautry, how would you update this section to clarify our unified stance? I.e. can you take a crack at a compromise?

For convenience, here is the section that’s being discussed:

> If you have a bugfix or new feature that you would like to contribute to tsoa, please find or open an issue about it first. Talk about what you would like to do. It may be that somebody is already working on it, or that there are particular issues that you should know about before implementing the change.

> We enjoy working with contributors to get their code accepted. There are many approaches to fixing a problem and it is important to find the best approach before writing too much code.

> Note that it is unlikely the project will merge refactors for the sake of refactoring. These types of pull requests have a high cost to maintainers in reviewing and testing with little to no tangible benefit.

**Comment by lukeautry** [comment] 2019-08-31 20:33
I think that's actually good and we could just add a clarifying point here:

> If you have a bugfix or new feature that you would like to contribute to tsoa, please find or open an issue about it first. Talk about what you would like to do. It may be that somebody is already working on it, or that there are particular issues that you should know about before implementing the change.
> 
> We enjoy working with contributors to get their code accepted. There are many approaches to fixing a problem and it is important to find the best approach before writing too much code.
> 
> In situations where the code is very hard to extend, we may want to refactor modules or redesign certain aspects of the project. The new design should be proposed and agreed upon in the attached issue. While we strongly value enhancements to code quality, significant refactoring should usually be reserved for situations where the non-refactored version of code would be too difficult to work with.

**Comment by HoldYourWaffle** [comment] 2019-09-01 11:17
> (Update: I accidentally clicked the close button because I was on mobile)

Happens to the best of us ;)

> So hopefully this clarifies that I believe deeply in refactoring, but that I think it must be done in a way that respects the time of the code reviewer. The contributor guidelines clarify that point.

I wasn't trying to imply that you don't like refactors at all, like you said they're needed for improvement. I was (and still am) referring to "banning" (in a very loose sense of the word) *standalone* improvements (in the form of refactors), not refactors in general.

Respecting the time and willingness of maintainers should always be a top priority, I definitely don't want people to rapid-fire (useless) refactors at you. I opened this issue because I felt like the original text of the guidelines felt a little "too restrictive" so to say. I don't *disagree* with them, I just think there's room for improvement to clarify our stance. I was hoping to start an open discussion on this, focused on "what is a pointless refactor" instead of stylistic changes and software development philosophy like in #445. So far it looks like it worked 😉

> Can you help me understand where you got the idea that we don’t want improvements? My counter argument:

I was referring to the original guideline text which felt too restrictive to me. Reading back I probably worded that in a just not very good way. What I meant to say was something like: I think we can all agree that we don't want to be as restrictive as the guidelines make it look, so maybe we should clarify the guidelines.

Please keep in mind that English is not my first language, so these kinds of 'miscommunications' will probably happen from time to time, I hope you can forgive me for that. I try to keep them to a minimum by proofreading everything I write about 3x before I submit but I unfortunately won't catch everything everytime.

> I specifically created an issue for the sole purpose of providing an avenue for you (@HoldYourWaffle) to be able to refactor the type resolver code that you find bothersome.

I'll get to it soon ;)

> This code isn't big enough to need this kind of bureaucracy for sanity

Whooooops I meant project, as in the amount of contributors affected. Like I said before, maintainer boundaries should be one of the top-priorities.
This might be another instance of miscommunication due to language barrier. I think perhaps 'bureaucracy' wouldn't be the best word to use here in English. What I meant to say was: this **project** (not code 😉) isn't at the size yet where the amount of contributors affected by a refactor is big enough that very strict guidelines such as TypeScript's would be suited. A refactor in such a big project can throw of hundreds of contributors at once, resulting in *developers* losing their sanity.

**I was not referring tot he sanity of maintainers while reviewing these kinds of PR's**. To be quite honest with you, before you mentioned that refactor PR's are a pain to review in a comment somewhere in #445 I hadn't even thought about that. I haven't done a lot of PR reviewing, so it just didn't immediately cross my mind that the diffs for these kinds of changes are a pain to review.

I think I've mentioned this before, but perhaps it would be a good idea to add some more maintainers to the project, so the volume of requests is carried by multiple people instead of just you (and a bit Luke). These people probably shouldn't have full merge capabilities, github's "triage" role would probably do the trick.

> But if a PR does not fix a bug or add a new feature, then it is by definition “refactoring for refactoring sake.” While the refactoring may be useful, its utility is less than that of a standard feature/bug PR. The contributor guidelines (that I took from elastic search’s page), do not state that refactor PRs “won’t” be merged, it only states that they are “unlikely.”

That last point is exactly what I hoped could be clarified, especially where the line is between "useful refactors" and "refactors for refactorings sake".
Personally I don't think PR's that don't explicitly fix a bug or add a feature unconditionally fall under the latter, but it's a reasoning I can get behind. However, in my opinion the guidelines didn't express this reasoning clear enough, which is why I opened this issue.

<br>

> I'm not opposed to standalone refactorings, and in fact, I think they should come in that form, but they should be tied into some specific feature initiative. (...)

I agree with Luke on this. Like I said before, I don't think standalone refactors/cleanups are *unconditionally* "bad", but that's up to the maintainer(s) to decide. I just felt like the original guidelines didn't clarify this well enough, hence this issue.

> That’s fine Luke, but as someone who only recently starting understanding the internals of tsoa, I would not be qualified to review most PRs that are purely refactoring. So I think I’m doing people a favor by essentially saying, “a refactoring PR might languish for a long time until Luke can check this out.”

Such a warning could be added to the guidelines 😉
I think this is another example of why more people reviewing stuff might be a good idea.

> However, if it’s a small, targeted refactor of code that I have worked in before, then I have more of a chance of being successful at assuring the quality of my review. But until my familiarity of the codebase grows, I found it important to clarify my limitations. Adopting the elastic search contributor guidelines was the best way for me to do so.

Don't get me wrong, I absolutely agree that you need to clarify and communicate your boundaries and needs. The only thing I was hoping for was an open discussion to clarify what the guidelines meant. Luke's clarification is definitely the step in the direction I was hoping for (as for the actual clarification suggested by Luke, I've put a comment on that in #458).

**Closed** 2019-09-01 14:13 UTC

**Comment by dgreene1** [comment] 2019-09-01 14:14
I merged the changes to the language that Luke requested.
