### ISSUE TITLE
Query param as collectionFormat

### ISSUE THREAD

**Issue by dmitrirussu** [lukeautry/tsoa#324] opened 2018-12-17 13:16 UTC
is possible to handle Query param as an collectionFormat?
My query param is an array of statuses[]=x&statuses[]=y&statuses[]=z
I do not see in documentation how I can add that kind of param
``
{
    "name": "statuses",
    "in": "query",
					"description": "statuses",
					"required": true,
					"type": "array",
					"items": {
						"type": "string"
					},
					"collectionFormat": "multi"
					}
``

**Comment by dgreene1** [comment] 2019-08-17 05:27
This is a duplicate of https://github.com/lukeautry/tsoa/issues/353, so we’ll track the issue there.

**Closed by dgreene1** 2019-08-17 05:27 UTC
