### ISSUE TITLE
express Request is undefined in TSOA route Controller

### ISSUE THREAD

**Issue by iasbm** [lukeautry/tsoa#533] opened 2019-11-25 10:05 UTC
Hello
I need to be able to access expressRequest in one of the TSOA controller.  But it is coming as UNDEFINED

## Sorting

* **I'm submitting a ...**
  - [ YES] support request

* I confirm that I
  - [YES ] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

I expect to receive a valid express.Request in TSOA Route Controller.

```yaml

```

```ts

```

## Current Behavior

express Request Object is undefined in TSOA Route controller.

```yaml

```

```ts
import { Route, Get, Post, Delete, Request, Response, Header, Body, Security, Controller } from 'tsoa';
import * as express from 'express';

@route('auth')
export class UserAuthController extends Controller {

@post('Login')
public async login(@Body() request: IUserLoginRequest, @Request() expReq: express.Request): Promise {
logger.debug('expReq is....'+expReq);
}
```

## Possible Solution

I expect to receive a valid express.Request in TSOA Route Controller. SO that i can access the object i have stored in app.locals.
But the logger statement prints the "expReq" as undefined...

## Context (Environment)
Version of the library: v 2.5.4 
Version of NodeJS: v10.16.3
Version of Type Script : v 3.7.2
* Confirm you were using yarn not npm : [NO ]

**Comment by dgreene1** [comment] 2019-11-25 13:52
So I can’t tell what the problem is with your code by reading it, but I can tell you that we have multiple unit tests that utilize the @Request decorator, so if this wasn’t working then tsoa wouldn’t be able to publish.

Maybe someone else can determine what’s wrong with your code. I can’t tell what’s wrong.

**Comment by dgreene1** [comment] 2019-11-25 13:53
If you’re willing to push your entire repository to its own github repo and send us a link, I can try to see what’s wrong.

Also, can you confirm that your are not use a custom handlebars template?

**Comment by iasbm** [comment] 2019-11-25 13:55
NO I am not using any Custom Handlebars template

**Comment by iasbm** [comment] 2019-11-25 14:57
below are relevant files...

**TSOA.JSON**
```
{
    "swagger": {
        "info": {
            "description": "A Login authorization and registration using jwt",
            "version": "1.0.0",
            "title": "User Login Auth and Registration"
        },
        "tags":[
            {
                "name":"auth",
                "description":"Access to updating a secured data"
            },
            {
                "name":"user",
                "description":"Operations about user"
            }
        ],
        "schemes": [ "http", "https" ],
        "securityDefinitions": {
            "api_key": {
                "type": "apiKey",
                "name": "access_token",
                "in": "header"
            }
        },
        "outputDirectory": "./dist",
        "entryFile": "./src/server.ts",
        "host": "localhost:3000",
        "basePath": "/api"
    },

    "routes": {
        "basePath": "/api",
        "entryFile": "./src/server.ts",
        "routesDir": "./src/middleware/server-config",
        "authenticationModule": "./src/business-layer/security/Authentication"
	},
	"ignore": [
		"**/node_modules/**"
	  ]
}
```
**Express.ts**

```
import "reflect-metadata";

import express from 'express';
import expressWs from 'express-ws';

import { setupLogging } from './LoggerSetup';

import { SCCServiceHub } from '../smart-cc/ServiceHub';
import config from 'config';
import * as https from 'https';
import * as fs from 'fs';
import path from 'path';

export class ExpressConfig {
  app: any;
  static:any;

  constructor() {

    this.app = express();
    const expWsInstance = expressWs(this.app);
    this.static = express.static;

    setupLogging(this.app);
    this.app.locals.ServiceHub = new SCCServiceHub();   
  }
}
```
**Server.ts**
```
import { ExpressConfig } from './middleware/server-config/Express';
import { logger } from './middleware/common/logging';
import { UniqueIDService } from './middleware/common/UniqueIDService';
import { ServiceKeys } from './middleware/smart-cc/ServiceKeyConstants'

import './service-layer/app-controllers/UserAuthController';
import './service-layer/app-controllers/AgentController';
import './service-layer/app-controllers/CSAdminController';
import './service-layer/app-controllers/C4HProfileController';

import {RegisterRoutes} from './middleware/server-config/routes';
import bodyParser from 'body-parser';

import  cors from 'cors';
import  cookieParser from 'cookie-parser';
import health from 'express-ping';
import path from 'path';
import { Request, Response } from 'express';
import expSession = require('express-session');
import * as swaggerUi from 'swagger-ui-express';
import './types';

import { CustomerConnectionHandler } from './middleware/smart-cc/customer/CustomerConnectionHandler';
import { AgentConnectionHandler } from './middleware/smart-cc/agent/AgentConnectionHandler';

let express = new ExpressConfig();
let objUniIDSrvc = new UniqueIDService();
let custWSConnHandler: CustomerConnectionHandler; 
let agentWSConnHandler: AgentConnectionHandler;

// For demo purposes we need to ignore self-signed certificate related warnings
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

try {
	const swaggerDocument = require('../dist/swagger.json');
	express.app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
} catch (err) {
	console.error('Unable to read swagger.json', err);
}
//End: To be Revisisted and uncomment the below after SWAGGER READY...

express.app.use(cors({
  origin: true,
  credentials: true,
}));
express.app.use(bodyParser.urlencoded({ extended: true }));
express.app.use(bodyParser.json());
express.app.use(health.ping());
express.app.use(express.static(path.join(__dirname, '/public')));

//Setting up express-session Middleware 
express.app.use(expSession({
    secret: 'MY_SECRET',
    genid:(req:any) => {
      return objUniIDSrvc.getUniqueID();
    },
    resave: false,
    saveUninitialized: true,   
  }))

//Register the app with all the TSOA generated Routes
RegisterRoutes(express.app);

export default express.app

```
**Start.ts**
```
//import app from '@server';
import app from './server'

import config from 'config';
import { logger } from './middleware/common/logging';

import * as https from 'https';
import * as fs from 'fs';
import path from 'path';

const port = config.get('Server.PORT');
const debugPort = config.get('Server.DEBUG');
let server: any;
server = app.listen(port, () => {

const expressHost =  server.address().address;
const expressPort =  server.address().port;
logger.info(`
    ------------
    Server Started!
    Express: http://${expressHost}:${expressPort}
    Health: http://${expressHost}:${expressPort}/ping
    Swagger Docs: http://${expressHost}:${expressPort}/docs
    Swagger Spec: http://${expressHost}:${expressPort}/api-docs
    ------------
`);
})
```

**UserAuthController.ts**

```
import { Route, Get, Post, Delete, Request, Response, Header, Body, Security, Controller } from 'tsoa';
import { IUserLoginRequest } from './requests/index';
import { IUserLoginResponse, IMessageResponse }  from './responses/index';
import { JwtService } from '../../business-layer/security/JwtService'
//import { createAuthToken } from '../../business-layer/security/token-helpers';
import { UserLoginDA } from '../../data-layer/data-agents/';
import { UserModel } from '../../data-layer/models/UserModel';
import { logger } from '../../middleware/common/logging';
import { AgentDA } from '../../data-layer/data-agents/';
import * as express from 'express';


@Route('auth')
export class UserAuthController extends Controller {

  private userLoginDA = new UserLoginDA();
  private objJWTService = new JwtService();

  @Post('Login')
  public async login(@Body() request: IUserLoginRequest, @Request() expReq: express.Request): Promise<IUserLoginResponse> {
    
      logger.debug('expReq is....'+expReq); //  This is printed as undefined
  }
```
**So, the last logger.debug prints 'expReq is.... undefined**

**Comment by dgreene1** [comment] 2019-11-29 18:26
@iasbm we can’t help you unless you create a github repo that shows the issue. Until then all we can do is ask you to try things. For instance, please tell us if the issue still reproduceable if you remove all of the express middleware (outside of bodyparser which is necessary). I’d be happy to try this for you, but I’ll need the link to a github repo where I can try it.

**Comment by dgreene1** [comment] 2019-12-12 19:22
@iasbm I'd like to repeat that this is not broken in our unit tests so that points to the error being within one of your express middleware. We'd be happy to dig into this further if you can create a github repo that we can pull down and run. However, since [this unit test](https://github.com/lukeautry/tsoa/blob/09b9eb3018f15b619af583e37123b664b117ff03/tests/fixtures/controllers/parameterController.ts#L113) shows that it's working we can confidently say that the `@Request` decorator returns a truthy object. So we will close this issue until you can submit a repository with your code. However, I would ask that you please try to diagnose this yourself first since there is a very strong chance that one of your middleware functions is unsetting/deleting the request object before the tsoa route is being hit.

**Closed by dgreene1** 2019-12-12 19:22 UTC

**Comment by Univac1107** [comment] 2020-01-15 21:08
I had the same issue with @Request and @Header. You must generate your routes again.

**Comment by veeral-patel** [comment] 2023-06-16 03:18
Had the same error. Need to re-generate routes after adding this annotation.

Maybe we can document this @dgreene1?
