### ISSUE TITLE
Omitted partials lose their partial property status

### ISSUE THREAD

**Issue by BottlecapDave** [lukeautry/tsoa#1191] opened 2022-02-18 08:02 UTC
## Sorting

- **I'm submitting a ...**

  - [x] bug report
  - [ ] feature request
  - [ ] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

## Expected Behavior

When omitting a property from a type which extends a partial of a type, I would expect the partial properties to still be optional (see `Pick_IUpdatableTest.Exclude_keyofIUpdatableTest.id__`).

```yaml
components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas:
        IUpdatableTest:
            properties:
                prop1:
                    type: string
                prop2:
                    type: boolean
                updatedOn:
                    type: string
                id:
                    type: string
            required:
                - updatedOn
                - id
            type: object
            additionalProperties: false
        Pick_IUpdatableTest.Exclude_keyofIUpdatableTest.id__:
            properties:
                prop1:
                    type: string
                prop2:
                    type: boolean
                updatedOn:
                    type: string
            required:
                - updatedOn
            type: object
            description: 'From T, pick a set of properties whose keys are in the union K'
        Omit_IUpdatableTest.id_:
            $ref: '#/components/schemas/Pick_IUpdatableTest.Exclude_keyofIUpdatableTest.id__'
            description: 'Construct a type with the properties of T except for those in type K.'
    securitySchemes: {}
info:
    title: TSOA
    version: 1.0.0
    description: 'Build swagger-compliant REST APIs using TypeScript and Node'
    license:
        name: MIT
    contact:
        name: unknown
openapi: 3.0.0
paths:
    '/{id}':
        patch:
            operationId: Update
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/IUpdatableTest'
            security: []
            parameters:
                -
                    in: path
                    name: id
                    required: true
                    schema:
                        type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Omit_IUpdatableTest.id_'
servers:
    -
        url: /
```

## Current Behavior

When omitting a property from a type which extends a partial of a type, the properties that should be optional are now required (see `Pick_IUpdatableTest.Exclude_keyofIUpdatableTest.id__`).

```yaml
components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas:
        IUpdatableTest:
            properties:
                prop1:
                    type: string
                prop2:
                    type: boolean
                updatedOn:
                    type: string
                id:
                    type: string
            required:
                - updatedOn
                - id
            type: object
            additionalProperties: false
        Pick_IUpdatableTest.Exclude_keyofIUpdatableTest.id__:
            properties:
                prop1:
                    type: string
                prop2:
                    type: boolean
                updatedOn:
                    type: string
            required:
                - prop1
                - prop2
                - updatedOn
            type: object
            description: 'From T, pick a set of properties whose keys are in the union K'
        Omit_IUpdatableTest.id_:
            $ref: '#/components/schemas/Pick_IUpdatableTest.Exclude_keyofIUpdatableTest.id__'
            description: 'Construct a type with the properties of T except for those in type K.'
    securitySchemes: {}
info:
    title: TSOA
    version: 1.0.0
    description: 'Build swagger-compliant REST APIs using TypeScript and Node'
    license:
        name: MIT
    contact:
        name: unknown
openapi: 3.0.0
paths:
    '/{id}':
        patch:
            operationId: Update
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/IUpdatableTest'
            security: []
            parameters:
                -
                    in: path
                    name: id
                    required: true
                    schema:
                        type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Omit_IUpdatableTest.id_'
servers:
    -
        url: /

```

```ts
import { Route, Patch, Body, Path, Controller } from 'tsoa';

interface IUpdatedOn {
  updatedOn: string;
}

interface IIdentifiable<TId> {
  id: TId;
}

interface ICoreTest {
  prop1: string;
  prop2: boolean;
}

interface IUpdatableTest
  extends Partial<ICoreTest>,
    IUpdatedOn,
    IIdentifiable<string> {}

@Route('')
export class TestController extends Controller {
  @Patch('{id}')
  public async update(
    @Path() id: string,
    @Body() data: Omit<IUpdatableTest, 'id'>
  ): Promise<IUpdatableTest> {
  }
}

```

## Possible Solution

N/A

## Steps to Reproduce

See provided ts code, where `tsoa spec-and-routes` are then performed on.

1. 2. 3. 4.

## Context (Environment)

Version of the library: 3.14.1
Version of NodeJS: 14.17.4

- Confirm you were using yarn not npm: [ ]

## Detailed Description

N/A

## Breaking change?

By fixing this bug, I guess it could result in other peoples specs potentially changing without realising.

**Comment by melvingaye** [comment] 2022-03-30 00:05
Experiencing this right now, did anyone find a workaround? Or Do I simply define the params in a new model and maintain two models?

```
interface Author {
id,
name,
dob
}

interface Book {
id, 
title,
author: Author
}

//  author properties are showing as required but book properties (excluding author) show up as optional
type BookCreationParams  = Partial<Book> & { author: Partial<Author> } 
```

**Comment by dpomerantz-jci** [comment] 2022-06-06 02:03
I believe I am experiencing this as well.  It can be seen through the following example:  https://github.com/dpomerantz-jci/tsoa-inheritance-poc.  Clone and then you will see that in both swagger.json and routes.ts, the type Business_IdOnly_Omitted, which is the type of the field UserWrite.business3, Fields which were previously marked as Optional are now required again.  This happens if I use Partial<T, K> or Sequelize's Optional<T, K>.  This seems to happen specifically when I use Omit<T, K> on a type with optional fields.  Typescript still acknowledges optional and required fields correctly, as can be seen in the method UserController.saveUser().  All four variables are able to be created without the optional fields being populated.

My specific use-case is one where I want to make **all** fields optional with predictable, known exceptions.  I have a work-around for it, which can be seen with the type Business_IdOnly_Omitted_IdOnly, where I alias the type and mark fields as optional (again).  This may help others.

I would like to be included on the roadmap for resolution so that we can stop using the work-around when able.

Thanks,

dmp

**Comment by dpomerantz-jci** [comment] 2022-06-06 21:14
I think I've sort-of identified the cause here, but it's beyond my understanding to resolve.  Hopefully this is enough to get the ball rolling.  As far as I can tell, the following code is supposed to set the required property to false based on an a setting in the inheritance hierarchy:

```
        else if (overrideToken && overrideToken.kind === ts.SyntaxKind.QuestionToken) {
            required = false;
        }

```

In my reference project, `overrideToken `exists, and informs the compiler to set required to false for the type `Business_IdOnly`.

When the type `business_IdOnly_Omit` is processed, `overrideToken `is undefined.

That token is supposed to be set by this line:

`            const mappedTypeNode = this.typeNode;
`

however it is being left as undefined for these omit types.  I'm not sure what is causing it not to set, but I think if the `typeResolver` can be fixed to appropriately set `typeNode` for fields within Omit, then it will fix this.

In a previous iteration of my reference project, I had a type reference instead of an interface to see if the interface was the problem, and I saw the same results with the type reference.

It's not getting the inheritance hierarchy as far as I can tell.

@WoH  Please review in case this helps.

**Comment by nickzylstra** [comment] 2022-07-29 21:18
also encountering this bug.  As a workaround, I manually redeclared a type with optional parameters to avoid using the 'Partial' utility type.  [Playground with code](https://www.typescriptlang.org/play?#code/PTAEGUEsFsAcBtIDNIFMAmpYCcD2AjeVaAKBFDLAElQCBnVbAN1VABcALAQzdH1060k7DqyS548XAHdIAOwDmoAMZcGdUA2Ltc7bJAULGI1pDp0ArqgBclUAEYAdKAt15SgApdsbSF3ig6JDYqMps8ACeoLKc8qAA8tCQvAC0CUlsADxePn7wmQCCADSgAOQ4uLAATKUAfLV2Vc6u7qBccm2IaqBxickiPNHdyiE8GNHJHKA5vv6gaVqgqAAeXHBEGvioUtIkbBGwrAWgALygAN4koNdYeLD21pps+opXNxXVj3TP7iQAviQ9gcjjM8qdpt5ZvkCg19odQAVQf4+mw2OMzijCkj4CVyncag1yAAVYF0EaQWBsUoaEJ0CQsTBw1joXCoDRyASgaA8ZRTIngeIFamgWn08ZMoHwkmHMn6SmIyF5FFozBnS43W6VewAfi+P1eAKZoH5goVuWRGRV4PV7zuDyeLwU-0B5AAslEKoRtNJRB1pLhsABrVoxPnA+IAJVdbTkmBNxziqgYPV4ongsA07QiuDkqDsdhoXFgh28OlA3BYS1j4wssB6HS4DvaRmNpPJlKw8C4ymZVjLnGZbIMcg0uGE8ZjcfDUYLmlchzCJhCwsbW1RxmkXAiJXwFl40CidPge8gObaxdQ3g0bF0-qDoHE2C5UVzGEzsdANBZclKqa4legAM83IXxoFYG9NEOD8z1iOhHHzcgqA6AdW0OSNo1dXB0G2EoUIAQh6dlQjZOhvCiLZVFcUw5GSPJIAAL1aFCPlHJ8GFRJjRFIcg4hQ5Qc2+bALDCANAhzX9ogDQMJkEFDpVQdDAiHBQOlgHg0WwEcKDsCc6AXScRVwPc2VAIxc2wHhTz9KTMw0FYFytUQQnzZQu3MVCFKjTDsPgY4bXID57HLbpG2wpAuAseBeCYfw+3Y+sTA8xSAGEJAsaAOmw-iLJvbA3kCvC9UdfL8UKh1fgBSVWG87YCniSkrLmNUSq1XVysUIpnSNGrfIjVAAEcLGCdF0mSTJ5PQnrilAQNUGzYQpvq3wc38BoqtAKaABEACFUrkZ4JCIbBktGXLwUWhqVoCAAyDasNqvrBuG9AXTAD4qkI0zUHMsZMHwKIUMRGg8GM4LYyOko6RjBEPBoKinxZEyOV4V9GV0ComEgbCU3WqagYjIy0Q8XBvm2rCogxDJMi23acwOyRGBOy9ctxd66nW+TZQpNg+ssKL3AKeTrTea5ArawSKo5gUCl5yLfEUQXgWFjUxaKyWdOlyDQgMkG0Q0MzGEss9EY0AA5eIiUk+9uns0JHMYYCwBIVy1A0CavPu+BtouN4ArtYLMyU8K5dAGLj1YeLeNEJKo1AVLjwypTsp4AMWvuMqJdeUXSrVg1AW6z3tqWxr4AAaTmjQzjxLVSlxwvi6u8FsUyTF3ddHrtpKDuG7kfxy4iOh6jrnztseoaQlVUasjbjuSlm+a7pHnvVvzpWO52vb6aOpmU6fM5u8u3ubsX7ZR4G8eMFezVqk+g2cvGf7EqBwzQe4cHGEh3R2hhuGGAR1l2SclRmWDGWNTBsGHqffGhNUDE1JuTcEmJ16032ngBmx1ToBlZvidmRpObth5myOW7htpC2airO04t9ROkNEreMst+aKFIUrchtotS5xoUAA)

simplified problem as I understand it:
```
type A = {
    prop1: string
    prop2: string
}

type APartialOmitted = Omit<Partial<A>, 'prop2'>
// Typescript's resolved type does not match TSOA's resolved type
type TypescriptAPartialOmitted = {
    prop1?: string
}
type TSOAAPartialOmitted = {
    prop1: string
}
```

**Closed** 2023-11-10 14:11 UTC
Labels: bug, help wanted
