### ISSUE TITLE
Typegoose/lerna integration : No matching module declarations found for mongoose

### ISSUE THREAD

**Issue by billouboq** [lukeautry/tsoa#940] opened 2021-03-15 12:48 UTC
## Sorting

- **I'm submitting a ...**

  - [ ] bug report
  - [ ] feature request
  - [x] support request

- I confirm that I
  - [x] used the [search](https://github.com/lukeautry/tsoa/search?type=Issues) to make sure that a similar issue hasn't already been submit

Hi, I'm trying to use tsoa with an express API. In my environment I'm using lerna, and my "models/interfaces" are in typegoose in different package than my express API.

When i'm trying to generate swagger json I have this error :

> Error: No matching module declarations found for mongoose

My tsoa config :

```json
{
  "entryFile": "src/index.ts",
  "noImplicitAdditionalProperties": "throw-on-extras",
	"controllerPathGlobs": ["src/new-controllers/**/*.controller.ts"],
  "spec": {
    "outputDirectory": "docs",
    "specVersion": 3
  },
  "routes": {
    "routesDir": "src"
  }
}
```

My only controller :

```ts
import { ICategory } from "@company/db-model/lib/schema/category";

interface CategoryFindPublicPro {
	results: ICategory[]
}

@Route("api/v1/user/categories")
export class CategoriesUserController extends Controller {
	@Get("{numResults}/{numPage}")
	public async findPublicPro(
		@Request() req: express.Request,
		@Query() since?: string,
	): Promise<CategoryFindPublicPro> {
            // some code
	}
}
```
my typegoose model :

```ts
import mongoose from 'mongoose';
import {
	prop,
	plugin,
	modelOptions,
	Severity,
} from '@typegoose/typegoose';
import { Base } from '@typegoose/typegoose/lib/defaultClasses';
import findOrCreate from 'mongoose-findorcreate';

@plugin(findOrCreate)
@modelOptions({ options: { allowMixed: Severity.ALLOW } }) // eslint-disable-line
export class ICategory extends Base<mongoose.Types.ObjectId> {
	@prop({ index: true })
	_ownerId?: mongoose.Types.ObjectId;

	@prop({})
	_externalId?: string;

	@prop({})
	svgImage?: string;

	@prop({})
	description?: string;

	@prop({ required: true, default: 'disabled' })
	name!: string;

	@prop({ type: mongoose.Types.ObjectId })
	_parentIds?: mongoose.Types.ObjectId[];

	@prop({ default: Date.now })
	creationDate?: Date;

	@prop({ default: Date.now })
	lastUpdate?: Date;

	@prop({ default: false })
	disabled?: boolean;
}
```

I'm using typegoose models in a lerna package, so maybe I have some configuration to make it work but cannot find documentation about it.

**Comment by WoH** [comment] 2021-03-21 14:04
Duplicate of the issues [here](https://github.com/lukeautry/tsoa/issues?q=is%3Aissue+lerna) https://github.com/lukeautry/tsoa/issues/784 and https://github.com/lukeautry/tsoa/issues/774 and https://github.com/lukeautry/tsoa/issues/876 and https://github.com/lukeautry/tsoa/issues/868 and also see https://github.com/lukeautry/tsoa/issues/868

**Closed by WoH** 2021-03-21 14:04 UTC
