### ISSUE TITLE
Support generic type parameter and return type

### ISSUE THREAD

**Issue by DuckMingBrother** [lukeautry/tsoa#27] opened 2016-12-14 08:11 UTC
Return type:
Current only support return `Promise<XXX>`, when return `Promise<Response<XXX>>` or `Response<XXX>`, cli throw error "No matching model found for referenced type T".

Paramter type:
use generic type in parameter can generate definition file, but swagger show parameter's schema is undefined.

Can you support it? thank you.

**Comment by lukeautry** [comment] 2016-12-15 17:10
I think this can be supported and it's a great idea. I'll look into it soon.

**Comment by alexey-pelykh** [comment] 2017-03-10 13:48
@lukeautry one thing I'm looking to address as well, as soon as other PRs are processed

**Comment by nenadalm** [comment] 2017-06-01 12:39
I see that support for this was merged, but if I try to use `Promise<ResultList<Resource>>` I get an error:
```shell
$ ./node_modules/.bin/tsoa swagger
There was a problem resolving type of 'T'.
There was a problem resolving type of 'ResultListResource'.
Error: No matching model found for referenced type T
```

with `ResultList` being
```typescript
interface ResultList<T> {
    data: T[],
}
```

version: `tsoa@1.1.8`

**Comment by judenaveenraj** [comment] 2017-06-13 16:04
@nenadalm +1 same here

**Comment by judenaveenraj** [comment] 2017-06-13 16:19
Just something i came across while fiddling with the above
**The following seems to work:**
interface ResultList<T> {
    data: T,
}

**The following doesn't, gives the above error that @nenadalm mentioned:**
interface ResultList<T> {
    data: T[],
}
**The following doesn't as well**
interface ResultList<T> {
    data: Array<T>,
}

**Comment by AndyGura** [comment] 2017-07-18 15:05
+1 on this! I can't make something like 
```
export interface IListPage<T> {
    pageIndex: number;
    totalPages: number;
    list: T[];
}
```
And use as result Promise<IListPage<MyCoolItem>>

**Comment by amozh** [comment] 2017-08-30 08:20
+1, i have the same issue

**Comment by AndyGura** [comment] 2017-10-22 21:40
@lukeautry Hello, anytning on this? Its been sitting there dormant for a while

**Comment by fhewitt** [comment] 2017-11-15 20:19
+1, same issue here. This seems a particularly important feature for code maintenance.

**Comment by ChamNouki** [comment] 2018-04-10 16:38
Hello, still have a kind a similar issue :
```sh
There was a problem resolving type of 'T'.
There was a problem resolving type of 'JsonApiResourceT'.
There was a problem resolving type of 'JsonApiWrapperUserAttributes'.
Generate routes error.
 Error: No matching model found for referenced type T.
    at new GenerateMetadataError (/Users/thibaut/Documents/poc/jsonapi-serializer/node_modules/tsoa/dist/metadataGeneration/exceptions.js:17:28)
    at getModelTypeDeclaration (/Users/thibaut/Documents/poc/jsonapi-serializer/node_modules/tsoa/dist/metadataGeneration/resolveType.js:419:15)
    at getReferenceType (/Users/thibaut/Documents/poc/jsonapi-serializer/node_modules/tsoa/dist/metadataGeneration/resolveType.js:280:25)
    at resolveType (/Users/thibaut/Documents/poc/jsonapi-serializer/node_modules/tsoa/dist/metadataGeneration/resolveType.js:95:25)
    at /Users/thibaut/Documents/poc/jsonapi-serializer/node_modules/tsoa/dist/metadataGeneration/resolveType.js:496:23
    at Array.map (<anonymous>)
    at getModelProperties (/Users/thibaut/Documents/poc/jsonapi-serializer/node_modules/tsoa/dist/metadataGeneration/resolveType.js:462:14)
    at getReferenceType (/Users/thibaut/Documents/poc/jsonapi-serializer/node_modules/tsoa/dist/metadataGeneration/resolveType.js:281:26)
    at resolveType (/Users/thibaut/Documents/poc/jsonapi-serializer/node_modules/tsoa/dist/metadataGeneration/resolveType.js:92:25)
    at resolveType (/Users/thibaut/Documents/poc/jsonapi-serializer/node_modules/tsoa/dist/metadataGeneration/resolveType.js:69:30)
```

I use tsoa in version 2.1.4.

Here is my code :
```typescript
@Route("users")
export class UsersController extends Controller {
    @Get("{id}")
    public async getUser(
        @Path("id") id: number,
        @Query() name?: string
    ): Promise<JsonApiWrapper<UserAttributes>> {
        const user = await UserService.get(id);
        return SerializerService.serialize(user);
    }

    @SuccessResponse("201", "Created")
    @Post()
    public async createUser(
        @Body() requestBody: UserCreationRequest
    ): Promise<JsonApiWrapper<UserAttributes>> {
        const user = await UserService.create(requestBody);
        this.setStatus(201); // set return status 201
        return SerializerService.serialize(user);
    }
}
```

and my Models :
### User.ts
```typescript
export interface User extends UserAttributes {
    apiId: number;
}

export interface UserAttributes {
    email: string;
    name: Name;
    status?: Status;
    phoneNumbers: string[];
}

export type Status = "Happy" | "Sad";

export interface Name {
    first: string;
    last?: string;
}

export interface UserCreationRequest {
    email: string;
    name: Name;
    phoneNumbers: string[];
}
```
### JsonApiWrapper.ts
```typescript
export interface JsonApiWrapper<T> {
    data?:
        | JsonApiResource<T>
        | Array<JsonApiResource<T>>
        | JsonApiResourceIdentifier
        | JsonApiResourceIdentifier[]
        | null;
    error?: JsonApiError[];
    meta?: JsonApiMeta;
    jsonapi?: any;
    links?: JsonApiWrapperLinks;
    included?: Array<JsonApiResource<T>>;
}
```
### JsonApiError.ts
```typescript
export interface JsonApiError {
  id?: string;
  links?: JsonApiErrorLinks;
  status?: string;
  code?: string;
  title?: string;
  detail?: string;
  source?: JsonApiErrorSource;
}

export interface JsonApiErrorSource {
    pointer: string;
    parameter: string;
    meta: JsonApiMeta;
}
```
### JsonApiMeta.ts
```typescript
export interface JsonApiMeta {
    [key: string]: any;
}
```
### JsonApiResource.ts
```typescript
export interface JsonApiResource<T> {
    type: string;
    id?: string;
    attributes?: T;
    relationships?: JsonApiRelationships;
    links?: JsonApiResourceLinks;
    meta?: JsonApiMeta;
}

export interface JsonApiResourceIdentifier {
    type: string;
    id: string;
    meta?: any;
}
```
### JsonApiRelationships.ts
```typescript
export interface JsonApiRelationships {
    [key: string]: JsonApiRelationship;
}

export interface JsonApiRelationship {
    links: JsonApiLinks;
    data: JsonApiResourceIdentifier | JsonApiResourceIdentifier[] | null;
}
```
### JsonApiLinks.ts
```typescript
export interface JsonApiLinks {
  self?: string | JsonApiLinkObject;
  related?: string | JsonApiLinkObject;
  [key: string]: string | JsonApiLinkObject;
}

export interface JsonApiLinkObject {
  href: string;
  meta: any;
}

export interface JsonApiResourceLinks extends JsonApiLinks {
  self: string | JsonApiLinkObject;
  related: string | JsonApiLinkObject;
}

export interface JsonApiErrorLinks extends JsonApiLinks {
  about: string | JsonApiLinkObject;
}

export interface JsonApiWrapperLinks extends JsonApiLinks {
  first?: string | JsonApiLinkObject;
  last?: string | JsonApiLinkObject;
  prev?: string | JsonApiLinkObject;
  next?: string | JsonApiLinkObject;
}
```

any update on this issue ?

**Comment by ChamNouki** [comment] 2018-04-11 07:41
So I tried to replace some generic parts of my interface and the following interface replacing JsonApiWrapper seems to work : 

### JsonApiUser
```typescript
export interface JsonApiUser {
    data?:
        | JsonApiResource<UserAttributes>
        | Array<JsonApiResource<UserAttributes>>
        | JsonApiResourceIdentifier
        | JsonApiResourceIdentifier[]
        | null;
    error?: JsonApiError[];
    meta?: JsonApiMeta;
    jsonapi?: any;
    links?: JsonApiWrapperLinks;
    included?: Array<JsonApiResource<UserAttributes>>;
}
```

I think it's the passing on of the generic type to another generic interface that bring on the issue.

**Comment by mazswojejzony** [comment] 2019-02-08 15:08
Bump. Any plans to fix this?

**Comment by lukeautry** [comment] 2019-02-08 15:11
This is definitely a desirable feature but it's some work to implement it handle all of the cases.

**Comment by andriykrasnychuk** [comment] 2019-03-22 09:25
+1

**Comment by dgreene1** [comment] 2019-08-19 23:53
Full support for generics was added in v2.4.10.

**Closed** 2019-09-05 19:40 UTC
Labels: enhancement, help wanted

**Comment by dgreene1** [comment] 2019-09-05 20:09
@ryankeener I know you already confirmed that this works, but I wanted to let you know that this fix/feature was just [released in v2.5.1](https://github.com/lukeautry/tsoa/releases). Can you let us know how it worked out for you?

Side note: we're looking for companies that want to be featured in tsoa's readme: https://github.com/lukeautry/tsoa/issues/464

**Comment by fhewitt** [comment] 2019-09-06 21:40
That's absolutely awesome. I love it!

But still have similar issue adding `extends`

```
export interface ThingContainerWithTitle extends GenContainer<TheThing> {
    title: string;
}

export interface GenContainer<T> {
    id: string;
    list: T[];
}
```

And I got

There was a problem resolving type of 'T'.
There was a problem resolving type of 'GenContainer'.
There was a problem resolving type of 'ThingContainerWithTitle'.

**Comment by dgreene1** [comment] 2019-09-06 23:14
@fhewitt would you be so kind as to make a separate issue for that scenario since the non-extended generic scenarios seem to be resolved?

**Comment by fhewitt** [comment] 2019-09-09 13:14
Can do that! > https://github.com/lukeautry/tsoa/issues/467

**Comment by mrgoonie** [comment] 2023-02-20 12:55
Hi @WoH @dgreene1, sorry for digging this but I think this issue isn't fully resolved (or maybe I'm doing something incorrectly).

```typescript
import { Get, Route } from "tsoa/dist";

interface ResponseObject<T> {
	status: number;
	data: T | any;
}

interface PingEntity {
	message: string;
}

class PingService {
	public async getMessage(): Promise<PingEntity> {
		return {
			message: "pong",
		};
	}
}

@Route("ping")
export default class PingController {
	@Get()
	async getMessage() {
		const svc = new PingService();
		const data = await svc.getMessage();
		let result: ResponseObject<PingService> = { status: 1, data };
		return result;
	}
}

```

When I try to generate the swagger json it throws this error:

```
There was a problem resolving type of 'ResponseObject<any>'.
Generate swagger error.
 Error: Debug Failure. False expression: Node must have a real position for this operation
```

But when I specified the type directly to `ResponseObject` (instead of using generic type), it will works normally:

```typescript
interface ResponseObject {
	status: number;
	data: PingEntity;
}
```

Here is the example repo: https://github.com/mrgoonie/express-swagger-typescript

Thanks,

**Comment by janhrastnik** [comment] 2023-08-03 16:08
@mrgoonie I had the exact same issue today, the problem is that the return type of `getMessage()` isn't explicitly typed.

```ts
@Get()
async getMessage() {
	const data: PingEntity = { message: "pong" };
	let result: ResponseObject<PingEntity> = { status: 1, data };
	return result;
}
```

Should be changed to:
```ts
@Get()
async getMessage(): Promise<ResponseObject<PingEntity>> {
	const data: PingEntity = { message: "pong" };
	let result: ResponseObject<PingEntity> = { status: 1, data };
	return result;
}
```

**Comment by douglasg14b** [comment] 2024-05-07 22:17
I don't think it's fully resolved, using a generic that extends a type results in the generic type itself erroring out with `GenerateMetadataError: No matching model found for referenced type TKey`

**Comment by blipk** [comment] 2024-09-03 08:49
I spent far too long chasing this similar problem updating the tsoa typeResolver.js helped me track it down:

```

        try {
            (0, flowUtils_1.throwUnless)(modelTypes.length, new exceptions_1.GenerateMetadataError(`No matching model found for referenced type ${typeName}.`));
        } catch(e) {
            console.log(type.getSourceFile().fileName)
            console.log(type.pos);
            throw e
        }
```

Turns out it was an issue with the Sequelize toJSON method and its generic return type and I had to do something like this:
```
    override toJSON(): InferAttributes<TModelClass, TInferAttrsOptions> {
        const values = Object.assign( {}, this.get() )

        return values
    }
```

However it still does not like my generic TModelClass type so I have to explicitly set it to the model class (which I can't as this is base class for my models - or I have to set it on all my models) OR I just set it to `object`

This makes me miss working with FastAPI
